### ISSUE TITLE
Support single device with multiple IPs

### ISSUE THREAD

**Issue by d-dsn** [mudape/iphonedetect#100]
I have 2.4Ghz and 5Ghz Wifi networks at home, and they assign a different MAC and IP for my phone.
Is there a way to support multiple IP-addresses for a single device?

**Comment by ildar170975** [comment]
Imho presenting a device with several IPs as several devices allows users to see a more detailed picture.
But I could agree that a possibility to "combine" IPs may be useful.

**Comment by RobertD502** [comment]
@d-dsn 
Do you have the Private Address option enabled on your phone for both networks? If so, that would explain the different MACs. Disable this option to have your MAC not be randomized (disabling this option is on a per-network basis, so, you'll need to connect to each network and disable this option individually).

If you set the static IP for the device on your DHCP server, you shouldn't be getting a different IP regardless of what band is being used. Only time I'd expect to see this is if you are using different VLANs for the two different WiFi bands.

**If you don't want to investigate why you're getting multiple IPs:** 
Since you are getting multiple devices for a single phone, you can get around this by assigning both device_trackers to the same Home Assistant user - that is if you're trying to track presence. Doing so will mark the Home Assistant `person` entity as home/away as long as one of the device trackers is considered at home/away (which one is used will be determined by what WiFi band your phone is connected to). For a further breakdown [here is the documentation.](https://www.home-assistant.io/integrations/person/)
