### ISSUE TITLE
IOS14 removes the iTunes "wake up" that this tracker uses.

### ISSUE THREAD

**Issue by jwelter1971** [mudape/iphonedetect#39]
iTunes has been depreciated and it seems so has this hook in IOS14.

You get the same behaviors as a ping or arp tracker - random false aways based on the device sleeping.

**Comment by mudape** [comment]
Thanks for the heads up!
Pity, the trick has been working well. 
Currently I'm on vacation and don't have any device on iOS 14 so can't test

**Comment by jwelter1971** [comment]
Yes this has been a great tracker.  Maybe it's just broken in the current ios14 beta and will come back before release.  Enjoy the vacation.

**Comment by danbayliss** [comment]
Have you tried going to the specific WiFi network and turning off 'Private Address'? This seems to have resolved it for me

**Comment by danbayliss** [comment]
Scratch that. It definitely doesn't resolve it :(

**Comment by mikesalz** [comment]
Well that stinks!  I absolutely love this integration!  Any ideas or suggestions for a replacement, or hopes that this might still work in iOS14?

**Comment by danbayliss** [comment]
I have moved over to Unifi tracker as suggested by @jwelter1971. It works really well with IOS14 and i've not had any false readings so far

**Comment by mikesalz** [comment]
Thanks @danbayliss! Are you referring to [this UniFi integration](https://www.home-assistant.io/integrations/unifi/)? Do you need Ubiquiti hardware in order to use it?

**Comment by danbayliss** [comment]
Yes I am. When you add it all your connected devices are added as entities and show as home/not_home. You do need a Ubiquiti AP to use it

**Comment by mikesalz** [comment]
Well that's too bad for me!  Thanks for the info, though.

**Comment by jwelter1971** [comment]
The way this tracker worked was using the hook that iTunes used for wifi sync.  This would allow iTunes to wake up a iOS device so it could push the wifi sync.  

But iTunes has been depreciated and replaced by Apple Music which uses a cloud pull sync so I suspect this hook was depreciated when they updated the network stack to use private MAC addresses.

We maybe SOL.  But Unifi does work ok for me, although a bit slower to detect a device leaving home, but just as fast to detect one coming home.

**Comment by danbayliss** [comment]
I’ve reduced the away time to 120 seconds and it still works fine. I’m going to try cutting it down a bit more to find out what’s the lowest time whilst not setting the device to away when its still at home

**Comment by mikesalz** [comment]
I tried the quantum_gateway integration today.  It seems to be just as accurate as this one.  Any downside to using it?

**Comment by MartnIV** [comment]
I was using iphonedetect as well.
I did the update yesterday, I wish I would have read this before.

**Comment by SentryMax** [comment]
I have updated a iPhone 7 Plus with ios14 and iphonedetect is working on it, the only thing is that I added the iphone to iphonedetect after the ios update so maybe removing, restarting and re adding may work? I haven't tried with my other devices yet.

**Comment by jwelter1971** [comment]
> I have updated a iPhone 7 Plus with ios14 and iphonedetect is working on it, the only thing is that I added the iphone to iphonedetect after the ios update so maybe removing, restarting and re adding may work? I haven't tried with my other devices yet.

When you leave your wifi area and come back the iPhone will use another Mac address if it's set to private addresses and then will fail to be detected.....

**Comment by SentryMax** [comment]
> 
> 
> > I have updated a iPhone 7 Plus with ios14 and iphonedetect is working on it, the only thing is that I added the iphone to iphonedetect after the ios update so maybe removing, restarting and re adding may work? I haven't tried with my other devices yet.
> 
> When you leave your wifi area and come back the iPhone will use another Mac address if it's set to private addresses and then will fail to be detected.....

In a period of 8 hours today i have turn on/off wifi on the iphone multiple times, turn on/off the iphone and the Airplane mode and iphonedetect still works every time. 
MAC address is set to private and the IP and DNS are set manually. I don't know how long is going to work but as of right now still working correctly.

**Comment by danbayliss** [comment]
I've setup iphonedetect from scratch and it seems to be working for me now with the GM release of IOS 14 and Private Address switched off.

**Comment by jaburges** [comment]
Amazing - this is by far the most effective way for tracking iOS devices! SOOO glad it still works :)

**Comment by kovaccs** [comment]
I think iphonedetect was the only easy to use device_tracker platform for the iphone. This option does not work properly with the IOS14 update, it does not see the phone in sleep mode, as it mentioned the comments before.
Do I want to know if there will be a solution to this, or do we have to look for some other solution?

There is no problem tracking other IP-based devices, only the sleeping iphone is a problem.
Do we get a response from the developer? (We hope His vacation is ended :-)  )    Today HA Core vers.: 0.117.2
kovaccsaba

**Comment by SentryMax** [comment]
iPhonedetect still works properly if you don’t use private address in your
iPhone, I am tracking 3 and they work. That said, they are 8 plus so I
don’t know if newer models have problems. The developer is not obligated to
do anything since nobody is paying him nothing

**Comment by mudape** [comment]
Hi @kovaccs 

As reported by @danbayliss and on my network the trick this integration uses seems to still work.
On my network we have iPhone 7, 8 and 11 all on iOS 14. All stay "home" throughout the day and night.

So what can be different on your system?
Are you checking the device_tracker or Person state? 
Maybe some other integration sets the Person away?


I've added "hostname_private" to also catch if targeted phone uses the Private MAC
So each Person has two device_trackers.

```yaml
device_tracker:
  - platform: iphonedetect
    consider_home: 60
    hosts:
      hostname1: 192.168.1.90
      hostname1_pm: 192.168.1.94
```
In history of device_tracker I can't see any unexpected away states.

**Comment by SentryMax** [comment]
Where do you add  "hostname_private" ?

**Comment by mudape** [comment]
In the yaml in previous post, see hostname1_pm (Sorry, I used different words in the example)
That needs to be added in the configuration.yaml file.
Home-Assistant needs to be restarted after adding the tracker.

Then in the GUI -> Configuration -> People add the "device_tracker.hostname1_pm" as a device to track for that user.

Make sure your DHCP(router) assigns the IP

**Comment by kovaccs** [comment]
Thank you guys, your reflections!

My iPhone11 device_tracker config is:
device_tracker:
  - platform: iphonedetect
    consider_home: 60
    new_device_defaults:
      track_new_devices: true
      # hide_if_away: false
    hosts:
      iph11: 172.30.1.66
      iph6: 172.30.1.64
      huawei_tablet: 172.30.1.65
... + many other hosts...

The iph11 is this problemetic host. 
The host checking in HA: ask device_tracker.iph11 entity

The today connection history of this phone is shown in this picture:
![image](https://user-images.githubusercontent.com/19958469/97868055-4ee0c380-1d0f-11eb-84b2-34ab4bb06ccd.png)

Try to understand hostname1_pm: xxx.xxx.xxx.xxx parameter in your config offer, but I don't know, what ip address can be written here, because I'm using preset fix IP-address on this phone. 

Please other suggesstions. Thank you.

**Comment by kovaccs** [comment]
> In the yaml in previous post, see hostname1_pm (Sorry, I used different words in the example)
> That needs to be added in the configuration.yaml file.
> Home-Assistant needs to be restarted after adding the tracker.
> 
> Then in the GUI -> Configuration -> People add the "device_tracker.hostname1_pm" as a device to track for that user.
> 
> Make sure your DHCP(router) assigns the IP

If I understand correctly, I have to configure two IP-address for one iPhone11 because it advertises two MAC-ADDRESS depending on whether it are asleep or awake. Is that okay?
That's why I have to check this two host devce_tarcker status in a logical OR relation? 
Or I have to use Person check? I haven't used this just device_tracker.iph11 so far.

**Comment by mudape** [comment]
Hi,

Please remove the **hide_if_away** line, that has been [removed](https://github.com/home-assistant/core/pull/32705) from Home-Assistant.

Interesting that you set a static IP on your iPhone, haven't tried that myself.
Do you also have a reservation in your DHCP?
I can imagine your DHCP gets confused when two different MAC addresses require the same IP when/if you switch to private MAC on the phone.

Just tested setting a static IP on my iPhone, weird that the wifi symbol doesn't show when using that!
This integration seems to work though.

> If I understand correctly, I have to configure two IP-address for one iPhone11 because it advertises two MAC-ADDRESS depending on whether it are asleep or awake. Is that okay?

The phone shouldn't change MAC when in deep sleep-state!
If not using static/manual IP on your iPhone you need two IP addresses in this integration.
That's because the **iPhone's private mac is seen as another device by your network**, independent of the phone "sleep"-state.
Above is only true when phones are switching between regular and private mac for your WiFi though.
If the phone always use the same mac, private or actual, one IP is enough as before iOS14.

Home-Assistant needs a way to link those network devices to the person you are tracking.
So, if the phone gets IP 10.0.0.15 when using non-private mac and with private mac it gets IP 10.0.0.78

```yaml
device_tracker:
  - platform: iphonedetect
    consider_home: 60
    hosts:
      phone: 10.0.0.15
      private_mac: 10.0.0.78
```
Then add both devices (_device_tracker.phone_ and _device_tracker.private_mac_) to the Person in Home-Assistant.
The person will be marked Home if one or more devices have that state.
When both is away, the Person is away.
(You may also add more trackers to the person, like the one from the Companion app)

**Comment by mudape** [comment]
The Private MAC does not change, it remains the same for the specific network.
It's a feature so that company x can't track if your phone has been to connected to their and other wifi networks they have data from.
Think of places like Starbucks: How many shops have you been to, when, for how long on so on.
Bad example maybe as they can track that via your payment, no one takes cash anymore..

**Comment by kovaccs** [comment]
Thank Magnus this detailed instructions!
Let see:
> Please remove the hide_if_away line, that has been removed from Home-Assistant.
This parameter's hashmarked!

> Interesting that you set a static IP on your iPhone, haven't tried that myself.
Do you also have a reservation in your DHCP? 

It was because of iphonedetect that I started using fixed ip on phones as well. In addition, the 32 slots have been filled in for MAC-ADDRESS assignment on my router  :-(

Anyway:
I hope I understand the two ip configuration examples, but I do not understand how to get the right MAC ADDRESSes to assign the IP addresses on my router. Can I read these from the phone? There are actually two MACs when I turn the Private Address switch on and off. These are?

**Comment by kovaccs** [comment]
I've done it, thanks for the help.

**Comment by mudape** [comment]
@jwelter1971 
Thanks for reporting this!

Looks like Apple so far hasn't gone for changing the private MAC and that the trick still works.
