### ISSUE TITLE
Device always registered as home

### ISSUE THREAD

**Issue by palmenmichiel** [mudape/iphonedetect#48]
Succesfully loaded the device tracker in home assistant, however, even if I turn off my WiFi on my phone and my device is gone from my active devices list on my router and I am unable to ping the static IP, 'iphonedetect' will still see the sensor as "home".
Not sure what I'm doing wrong here?

Already tried:
- Adding my mac address to the known_device tracker
- Shortening the scan interval to 5 seconds
- Only adding this device_tracker to my person
- Numerous reboots and reloads
- Already have the private mac address functionality disabled 

Not sure what I'm doing wrong here or what else I can try. Issue seems kinda related to #46 as I'm also running in docker, but in the same way does seem like a different issue as my docker IS in host mode and also states that my device is always home instead of away.

**Comment by mudape** [comment]
Hi @palmenmichiel ,

This integration blindly checks if there is a MAC address in the reply from ARP-table lookup.
Do you have multiple networks connected?

Might be that state and/or device needs to be added to
`output = subprocess.check_output('ip neigh show to ' + self.ip_address, shell=True)`

What does the log say if you set _custom_components.iphonedetect_ to debug?
See [logger](https://www.home-assistant.io/integrations/logger/#service-set_level) to turn change level.

**Comment by palmenmichiel** [comment]
I've added the logger, I do not see any errors... it just "ends" with:

2021-01-04 20:05:53 DEBUG (SyncWorker_1) [custom_components.iphonedetect.device_tracker] ip n output for iPhoneMichielDetect is: 192.168.178.55 dev eno1 **MACADDRESSOFMYPHONE** ref 1 used 0/0/0 probes 1 DELAY
192.168.178.55 dev wlp0s20f3 lladdr **MACADDRESSOFMYPHONE** used 0/0/0 probes 0 STALE
2021-01-04 20:05:53 DEBUG (SyncWorker_1) [custom_components.iphonedetect.device_tracker] Device iPhoneMichielDetect (192.168.178.55) is HOME

Could you explain what you mean with 'Might be that state and/or device...' as I don't really know what or where to change this?

**Comment by palmenmichiel** [comment]
One day later and it is again not working... Not sure what else to do.

**Comment by mudape** [comment]
strange! Must be something (not) happening in the ARP table

Could you please try updating line 54 in /config/custom_components/iphonedetect/device_tracker.py
`output = subprocess.check_output('ip neigh show to ' + self.ip_address, shell=True)`
with
`output = subprocess.check_output('ip neigh show to ' + self.ip_address +' dev eno1 nud reachable nud delay', shell=True)`

Why? Because now in the log wifi network reports the device ip as stale which this integration counts as home...
(the integration unfortunately only looks if the returned value contains a mac address)
Home-assistant needs to be restarted after the change.
The additions to the output filters to only use your NUC's wired network (eno1) and only look for when devices are either in state reachable or delay.
  
If you have ssh access to your home-assistant you can try the command directly there.
`ip neigh show to 192.168.178.55 dev eno1 nud reachable nud delay`

Please report back
