### ISSUE TITLE
Unuseable - state changing home/away with no movement of phone

### ISSUE THREAD

**Issue by GHSTUDIO1** [mudape/iphonedetect#51]
Looking at the log, I see that my two iphones are sensed as away and then a few seconds later home with no movement of the phone....eg. at night when we're sleeping.  This happened at leat 10 times last night. (sorry, I just started to look at all my logs, so I don't know if this is new or has been happening for a while.  My automations using this add-on have been off as I slowly develop them and I just turned them on last night.  (iphone XR software 14.4)

My guess is that the iphones, at least with the latest software are disconnecting and connecting to my wireless router.  Not sure iphonedetect can overcome this.

**Comment by mudape** [comment]
Hi @GHSTUDIO1 

Sorry to hear that you get false info from the integration.
I would suspect the network, mainly because that happens at my home from time to time.
We have multiple AP's and sometimes devices (other than our phones!) keeps jumping between them which seams to make the routers busy and phone connections are being dropped for a couple of seconds.
Usually solved by restarting the AP's.

Are you seeing this behavior every night?
