### ISSUE TITLE
Ios14.5 Not on the iPhone

### ISSUE THREAD

**Issue by ssyongka** [mudape/iphonedetect#63]
It has not worked properly since the ios14.5 update.

It works well on other iPhone that maintain the iOS14.4.

Do you ever need to set different settings?

**Comment by hurdigurdi** [comment]
can confirm. Since the latest update I am also no longer able to scan the zeroconf / mdns service of my iPhone.

Older iOS devices are still responding just fine.

Test command:
`nmap -sU -p 5353 -Pn --script dns-service-discovery <ip address>`

Not sure if there is a setting in iOS or an alternative service to be scanned though ..

**Comment by mudape** [comment]
I have seen that one of out devices, an iPhone 7, has been dropping out since 14.4 and 14.5.
Typically when roaming between Access Points (our house has 4 because walls are everywhere...)
So feels like Apple changed something regarding that.
That said our wifi hasn't been as stable as one would like the last couple of months...

The iPhone 11's on 14.5 and my 12 mini on 14.6, are working fine. 
Just like releases before 14.5.

Aren't you seeing the phone "home" at all?
Then I suggest you check that the phone really has the expected IP.

Of course Apple may have different settings based on where in the world you live, as modem firmware.

**Comment by hurdigurdi** [comment]
Hi @mudape 

the iPhone has a static IP assigned. Using "ping" platform for device tracking works fine when setting the consider_home interval to ~15 minutes. 
Using iphonedetect the devices never show. We have 2 iPhones in the mix: 11 pro and 12 mini on iOS 14.4.2, both never appear.

As mentioned, attempting a UDP connect on 5353 is filtered on both devices. ICMP pings do respond fine though. 

So yeah, they must have changed something in regards to security in iOS - at least in Europe/Germany

**Comment by k8gg** [comment]
![image](https://user-images.githubusercontent.com/25398491/121098663-a475d500-c7f6-11eb-8be6-db2e8950e2a2.png)
Here's what I see as of today, tracking on the same iPhone. The first line being the home/away data feed per my router, and the 2nd line the feed per this integration, over last ~8 hours.

**Comment by mudape** [comment]
In _/config/custom_components/iphonedetect/const.py_ uncomment `4: "STALE",` (line 4) from the HOME_STATES dictionary.
Home-Assistant then needs to be restarted

Think that will help flag the device as home but will increase time before detecting as away.

**Comment by dominikhoebert** [comment]
> In _/config/custom_components/iphonedetect/const.py_ uncomment `4: "STALE",` (line 4) from the HOME_STATES dictionary.
> Home-Assistant then needs to be restarted
> 
> Think that will help flag the device as home but will increase time before detecting as away.

I guess I have the same problem as above.
![Screenshot 2021-07-21 135225](https://user-images.githubusercontent.com/42839893/126486743-bfc5449d-56bc-42d6-b314-bacdeeb771a3.png)
Works really well (thanks for the great work!) with iPhone 6s iOS 14.6 (lower bar).
A lot of disconnects with iPhone X iOS 14.6 (upper bar, should be similar to lower).
Fix with uncomment of line 4 didn't help.

**Comment by mudape** [comment]
Hi @dominikhoebert 
What I've noticed is that recently iPhone's that supports 5Ghz WiFi takes along time to roam between AP's.
They also seems to be confused when the 2.4 and 5Ghz SSID have the same name, switching a lot between them.
What I've done that looks to help:
- Separate the 2.4 and 5Ghz network and only use one of them on the phone.
- Make sure the 'consider_home' is greater than 30 seconds.

**Comment by dominikhoebert** [comment]
Thank you for your Answer. I tried it now for a while, unfortunately it did not solve the issue.

**Comment by mudape** [comment]
Interesting/weird that iPhone X seems to behave different than other Apple devices.
At this point I don't know what else to try, don't have access to an iPhone X.

When our network and Home-Assistant host is working our phone's state is reported correctly.
So, not something in iOS 14 that stops this for iPhone 8, 11 or 12.

**Comment by mudape** [comment]
Stale and beyond this integration
